### ISSUE TITLE
Minor hiccup during installation

### ISSUE THREAD

**Issue by guolin1** [som-shahlab/ehr_ml#11]
I got the error `Could not build wheels for ehr-ml which use PEP 517 and cannot be installed directly` after following the installation guide in the documentation:

`conda create -n env_name python=3.9 bazel gxx_linux-64 -c conda-forge`
`conda activate env_name`
`pip install git+https://github.com/som-shahlab/ehr_ml.git`

This seems to have been caused by an outdated CMAKE version, and was fixed by upgrading CMAKE via `pip install cmake --upgrade` prior to running the installation. I wonder if it's worth updating the documentation in case others run into similar issues.

**Comment by Lalaland** [comment]
Thanks for the feedback. I think the solution here is to fix the docs such that we install cmake within conda. Thanks for the report!
