### ISSUE TITLE
Rename `StrideDataset` to something more generic

### ISSUE THREAD

**Issue by jason-fries** [som-shahlab/ehr_ml#19]
"Stride" is deprecated and confusing terminolog. `StrideDataset` should be renamed to something more general, e.g.,  `TimelineDataset`, `PatientTimelines` ? Open to suggestions here.

**Comment by woffett** [comment]
StrideDataset has been renamed to PatientTimelineDataset (its associated classes have also been renamed to PTDatasetIterator, PTDatasetBatch, etc.) in the newest PR.
