### ISSUE TITLE
Patient ID not found in timeline

### ISSUE THREAD

**Issue by bechlerk** [som-shahlab/ehr_ml#29]
Receiving below error. I tried uninstalling and reinstalling ehr_ml (I believe I did this correctly) but the same error occurs. 
<img width="1124" alt="Screen Shot 2022-01-11 at 4 59 26 PM" src="https://user-images.githubusercontent.com/61995037/149045245-e4cfeeee-0d1d-4a8b-b1a5-607e72d97a75.png">

**Comment by Lalaland** [comment]
Closed as an issue with the piton repository.
